# Generated by Django 3.1.12 on 2022-09-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='user_n',
        ),
    ]
